### PR TITLE
New Convolution Method

### PR DESCRIPTION
**Pull request by KRappaport**
Added new convolution function conv_2d_naive that can do 2D convolution on 3D inputs.  This new function uses a different approach to ordering the input and kernel matrices to match up the correct indices for convolution than the method used in naive_3d_conv_2.
Also added a script to check the convolution results from conv_2d_naive against those of convn (MATLAB's convolution function) in order to ensure that conv_2d_naive implements the convolution correctly.

### CODE REVIEW

**Comment by simchaherschman** [comment]
I wasnt able to follow it all but i think i got the jist of it. Really nice code. Thank you for te effort. 
I would like to agree to this pull request

**Review by simchaherschman — APPROVED** [review]
From what i understand, you are basing the direction of the for-loops based on location in the resulting matrix. I think its wise.

I dont quite follow all of the code for the "start_row" and "last_row" logic, as well as that for column, but I understand the direction of thinking.
Maybe we can go thru it together in person.

The check_correctness is a good idea.

**Comment by KRappaport** [comment]
The idea of "start_row" and "last_row" is to make sure that the range indices  used are within the bounds of both the input and kernel.  Similar explanation applies for column.  

I can easily explain it in person by writing out an example showing what is happening.

**Comment by simchaherschman** [comment]
Yeah I understood that much, just confused about the details

**Pull request merged**
